### ISSUE TITLE
Request Permisson Page

### ISSUE THREAD

**Issue by devrimyatar** [JanssenProject/jans#1480]
**Describe the bug**
In request permission page:
1 ) image is missing
2) requester is missing, instead `{} is requesting permission to do the following` is displayed

**To Reproduce**
1. Install Jans server
2. Start CLI
3. Request an item
4. Go device authorization page, enter code
5. Login as admin
6. You will see **Request Permisson** page as follows

![Screenshot_2022-05-31_14-41-03](https://user-images.githubusercontent.com/6398752/171165900-ea88ac15-d90a-4d48-abaa-afd9b5ea641e.png)

**Comment by manojs1978** [comment]
![image](https://user-images.githubusercontent.com/5729240/178197348-0690df37-7143-4bdf-9950-4d5740484ead.png)
image is still not loading

**Comment by jmunozherbas** [comment]
I found this problem is due to LocalizedString implementation.
![2022-07-14_02-50](https://user-images.githubusercontent.com/45716853/178927403-45ecb804-46bc-4788-ad30-926e7535c6f0.png)
![2022-07-14_02-55](https://user-images.githubusercontent.com/45716853/178927470-17e70e91-2ccd-4a34-8bd4-423e2a29bf26.png)

Who could help me to understand the way show this data type correctly?

I have tested a way to show:
https://github.com/JanssenProject/jans/commit/5cdc8348fdbc47707d4399e3b715c6d24236201c

**Comment by yuriyz** [comment]
After simplification as described by @yurem on which I guess all agreed we wouldn't need workaround.

See https://github.com/JanssenProject/jans/issues/1765#issuecomment-1184162092

**Comment by devrimyatar** [comment]
Fixed
![image](https://user-images.githubusercontent.com/6398752/213658972-9f9e9415-4724-47cf-9966-91b0392fa8c5.png)
