### ISSUE TITLE
Add unit tests to jans-fido2

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#240]
Currently, jans-fido2 module doesn't have unit tests. It is has been tested using integration(conformance) tests using [FIDO alliance tools].

We need to write low level unit tests that can be executed during each CI build.

**Comment by maduvena** [comment]
1. During Fido2 server development I used Conformance Self‐Validation Testing tool: https://fidoalliance.org/certification/functional-certification/conformance/

2. Instruction: https://builds.fidoalliance.org/FIDO%20Conformance%20Tools%20instructions.pdf

After running exe file it install it into <user_rpfile>\AppData\Local\Programs\fido-conformance-tools-electron. You can copy this folder to run it next time without install phase
Here is link: https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/v1.7.10/ I wrong link in second message

**Comment by Milton-Ch** [comment]
En `jans-auth-server`, utilizamos `TestNG`.
Deberiamos usar tambien en `fido2`?

**Comment by ossdhaval** [comment]
@Milton-Ch To me, since we are writing test cases from scratch, TestNG should be the choice. We should strive for uniformity in our toolset unless the nature of the module warrants otherwise. @yurem can opine on that as the code owner.

**Comment by Milton-Ch** [comment]
Reviewing the tests that already exist in `fido2`, they are written with `JUnit`.

![image](https://user-images.githubusercontent.com/86965029/232376353-c5c8154f-5498-43ff-9f19-1d8adb7401f2.png)

**Comment by Milton-Ch** [comment]
@yurem 
I am going to create `PR` containing 3 to 6 unit tests.
If I upload everything to a single `PR`, it would be too long to review.

**Comment by ossdhaval** [comment]
I think @yurem can answer that better than I do. 

In my view, important end-to-end functionalities should take priority. In doing so, you might write tests that are actually integration tests rather than unit tests which typically test one specific method. But still, I think it is important to have these broader tests in place first because they give us much more confidence. 

If the tests for end-to-end functionalities already exist then you can take up granular methods that are still not covered.

**Comment by Milton-Ch** [comment]
I am reopening this `issue`, to upload some unit tests that have been suggested in the `#service_fido` channel.

- [x] `io.jans.fido2.service.verifier`: Completed with this additional PR #4782
- [ ] `io.jans.fido2.service.sg`: This package contains 4 classes in total, a quick estimate can take about 3 to 4 days.
- [ ] `io.jans.fido2.service.processor`: This is the package that has more classes, and many methods to perform unit tests.

In my opinion, perhaps we should be adding unit tests as we are solving issues, since surely in some cases, we will touch a lot of code and there we can take advantage to perform the corresponding unit tests.
