### ISSUE TITLE
fix(jans-config-api): fix code scanning alert - GHSA-3mc7-4q67-w48m high vulnerability for snakeyaml package

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#2639]
Tracking issue for:
- [ ] https://github.com/JanssenProject/jans/security/code-scanning/1122

**Comment by pujavs** [comment]
**Analysis:**karate-junit5 has dependency on snakeyaml. karate-junit5 version `0.9.5` version currently used. The latest version of karate-junit5 also had same and other vulnerability. 

**Resolution:**  Explicitly added suggested fixed version of snakeyaml that is `1.33` rather than upgrading to latest karate version as its dependencies all have known vulnerabilities.
