### ISSUE TITLE
fix(jans-config-api): organization update returns 500

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#3019]
When updating the organization, the backend returns a 500 error.

Payload:
```
[{"op":"replace","path":"/dn","value":"o=janssen"},{"op":"replace","path":"/displayName","value":"TestDisplayName"},{"op":"replace","path":"/description","value":"TestDescription"},{"op":"replace","path":"/member","value":"yes"},{"op":"replace","path":"/organization","value":"TestOrga"},{"op":"replace","path":"/managerGroup","value":"TestManagerGroup"},{"op":"replace","path":"/shortName","value":"TestShortName"},{"op":"replace","path":"/organizationTitle","value":"TestOrganizationTitle"},{"op":"replace","path":"/baseDn","value":"o=janssen"}]
```

Exception on server:
```
com.github.fge.jsonpatch.JsonPatchException: no such path in target JSON document
	at com.github.fge.jsonpatch.ReplaceOperation.apply(ReplaceOperation.java:66)
	at com.github.fge.jsonpatch.JsonPatch.apply(JsonPatch.java:149)
	at io.jans.configapi.core.util.Jackson.applyPatch(Jackson.java:69)
	at io.jans.configapi.core.util.Jackson.applyPatch(Jackson.java:55)
	at io.jans.configapi.rest.resource.auth.OrganizationResource.patchOrganization(OrganizationResource.java:71)
	at io.jans.configapi.rest.resource.auth.OrganizationResource$Proxy$_$$_WeldSubclass.patchOrganization$$super(Unknown Source)
```

**Comment by pujavs** [comment]
JsonPath not returning the error of missing path, this will need custom handling of each operation to send the operations 1 by one and report missing path.
For time being added exception reporting.
On exclusively testing the operation locally found that
1. attribute name should be `member` rather `memberOf`. Also value of `member` should be valid `DN`
![image](https://user-images.githubusercontent.com/43700552/202695897-61a42fd3-f0b5-4f74-a66a-dc2324b311a6.png)

2. `organizationTitle` attribute was removed as per issue#https://github.com/JanssenProject/jans/issues/2756
![image](https://user-images.githubusercontent.com/43700552/202695670-79d92b15-4a7b-4ed4-a466-4981d734cc70.png)

3.  If a attribute has null value in DB then as per JSON-PATCH documentation we should use `add` operation rather than `replace`.  Will also try to handle this in custom logic

**Comment by pujavs** [comment]
@moabu, is there some unaddressed aspect pending for this issue?

**Comment by moabu** [comment]
Nope. Great work thanks . I'm closing this one
