### ISSUE TITLE
fix (jans-config-api): openApi clients do not send error response body

### ISSUE THREAD

**Issue by duttarnab** [JanssenProject/jans#3320]
For example, if we access config-api (on a rest client) to save oidc client without `redirect_uri` then we get following response.

```
{"code":"OCA001","message":"A required attribute is missing.","description":"The attribute redirectUris is required for this operation"}
```

But the OpenApi client do not send this error information. It just sent this error :

```
Error: Bad Request
    at Request.<anonymous> (client.js:452:1)
    at Emitter.emit (index.js:145:1)
    at xhr.onreadystatechange (client.js:761:1)
```

**Comment by pujavs** [comment]
@duttarnab, tested via jans-cli python and able to get the correct descriptive error message in response.
Request you to please re-check and revert
![image](https://user-images.githubusercontent.com/43700552/211819095-645757f7-bc28-49b0-b921-02927212388f.png)

**Comment by mjatin-dev** [comment]
@pujavs we are getting this error in the network tab as well. but in the code we are calling all the api's using `jans_config_api` and from the jans_ap function we are not getting this error in the cache.

**Comment by pujavs** [comment]
@mjatin-dev, please share more info as to how i can replicate the issue, jans-api function, test client, test environment details, etc

**Comment by mjatin-dev** [comment]
@pujavs From the `jans_api` I am getting the function ie shown in the picture function named 'postOauthOpenidClient' and in the return I am getting data or the error if I am getting data then it works fine but in the case of error I an not getting anything so I need error to be returned there so that we can show the same error to the user.
<img width="686" alt="Screenshot 2023-01-23 at 10 02 28 AM" src="https://user-images.githubusercontent.com/32476704/213966548-85f1c452-4583-42ec-ada9-ab85f8701b3e.png">

**Comment by pujavs** [comment]
got it, fixing

**Comment by pujavs** [comment]
@mjatin-dev, checked in changes for the same, request you to check and confirm

**Comment by pujavs** [comment]
@duttarnab, if the fix is working fine can i close the issue?

**Comment by jv18creator** [comment]
@pujavs, I think we can close this issue now since we are seeing the same error on the UI that is sent from the server. Thanks.
![Screenshot 2023-12-28 at 1 12 43 PM](https://github.com/JanssenProject/jans/assets/64732692/536e3f31-8aa1-428f-9f01-d140df97069d)
