### ISSUE TITLE
fix: feature flag for redirectUrisRegexEnabled not properly configured

### ISSUE THREAD

**Issue by ossdhaval** [JanssenProject/jans#3779]
Close this issue if [redirectUrisRegexEnabled](https://github.com/JanssenProject/jans/blob/2be2a0346d7ed0541bb540e3c2ff32aa3a04dcf7/jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java#L404) wasn't supposed to be a `feature flag`. And also remove the code comment that says `Feature Flag`

But like the code comment mentions, if the intention was to create a feature flag then it has to be correctly managed through [FeatureFlagType](https://github.com/JanssenProject/jans/blob/2be2a0346d7ed0541bb540e3c2ff32aa3a04dcf7/jans-auth-server/model/src/main/java/io/jans/as/model/common/FeatureFlagType.java) class, just like other feature flags. Currently, this integration is missing.

**Comment by yuriyz** [comment]
Via feature flag we turn on/off big parts of AS, like: uma, ciba, userinfo, etc. All tiny flags which influence tiny functionality should not be called feature flag. Otherwise we will flood feature flags with all our boolean configuration properties. Closing this ticket, `redirectUrisRegexEnabled` is not feature flag
