### ISSUE TITLE
feat(jans-fido2): Attestation and Assertion of Windows Hello platform authenticator

### ISSUE THREAD

**Issue by maduvena** [JanssenProject/jans#4141]
Following are the issues to be fixed:

**Attestation** : the flow proceeds correctly to TPM Processor
1. OID mismatch 
```
java.security.SignatureException: Signature encoding error
    at sun.security.rsa.RSASignature.engineVerify(Unknown Source)
    at java.security.Signature$Delegate.engineVerify(Unknown Source)
    at java.security.Signature.verify(Unknown Source)
    at com.cryptography.VerifyDkimSignature.main(VerifyDkimSignature.java:54)
Caused by: java.io.IOException: ObjectIdentifier mismatch: 1.3.14.3.2.26
    at sun.security.rsa.RSASignature.decodeSignature(Unknown Source)
   ``` 
   Fix:  change https://github.com/JanssenProject/jans/blob/86a7f18f188af9a3eb4cf4f40c7531358b277d42/jans-fido2/server/src/main/java/io/jans/fido2/service/verifier/SignatureVerifier.java#L92 to
   ```
   Signature signatureChecker = Signature.getInstance("SHA1withRSA");
   ```
After this, failures at every step of verification.
Useful References - 
1. https://fy.blackhats.net.au/blog/html/2020/08/24/windows_hello_in_webauthn_rs.html
2. https://github.com/microsoft/InventorySample/tree/master/docs/WindowsHello

**Comment by Milton-Ch** [comment]
According to the documentation there are 2 versions of `TPM`:
- `TPM 1.2`: Supports `SHA-1`.
- `TPM 2.0`: Supports `SHA-256`.

The tests that we have been doing with the @maduvena device, it behaves as `TPM 1.2`, because at the moment of verifying the hash instantiating `SHA-256` it gives verification error, but if we use `SHA-1` it works normally.

And here we have another problem, the method that performs the validation of extra data gives error https://github.com/JanssenProject/jans/blob/main/jans-fido2/server/src/main/java/io/jans/fido2/service/processor/attestation/TPMProcessor.java#L165
![image](https://user-images.githubusercontent.com/86965029/230382670-e919c0d9-283f-4e90-ab81-3368f1dc4175.png)

**Comment by yurem** [comment]
Is there flag which specify TPM version in request? In this case we can move TPMProcessor.java code into abstract BaseTPMProcessor.java and use it as base for 2 TMP processors

**Comment by Milton-Ch** [comment]
Checking `TPM 2.0` supports `SHA-1` and `SHA-256`, the difference is the `alg` field of `attStmt` where `-257`=SHA-256 or `-65535`=SHA-1 can come in.

**Comment by Milton-Ch** [comment]
@yurem

You can perform tests with `FIDO Conformance Tools`
I have uploaded this PR #4603
