### ISSUE TITLE
fix(jans-tui): smtp test failed still showing status code 200

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#4699]
**Describe the bug**
smtp test failed still showing status code 200

**To Reproduce**
1. install jans
2. launch tui
3. add smtp details and save
4. test smtp server
5. See error

**Expected behavior**
should get correct status details

**Screenshots**
![image](https://user-images.githubusercontent.com/5729240/233926772-ad623128-a486-4aa1-9e03-54c6e70e37f9.png)

**Desktop (please complete the following information):**
  - OS: suse 
  - Version 15 sp 4
  - DB mysql 
  - jans 1.0.13. nightly

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
config-api-erver is returning **False**,  nothing wrong here

**Comment by pujavs** [comment]
@manojs1978, i checked with @smansoft and he was kind enough to share the details.
SMT test functionality is working as expected. Also note that the status code will always be 200 with response as `true` or `false` based on the SMTP test result.
SMTP test works fine if you use Gmail App password and use it as `SMTP Password` rather than Gmail Web Login Password.
To generate the App Password refer https://www.getmailbird.com/gmail-app-password/
**Screenshots:**
![image](https://user-images.githubusercontent.com/43700552/234920830-8efafb8b-36c5-4af1-8a35-22236c71ddbf.png)


**App Password:**
![image](https://user-images.githubusercontent.com/43700552/234921075-6176ad27-614b-4af4-93fa-dcd35bd73035.png)
 

Assigning the issue back to you for testing and closing the issue.

**Comment by manojs1978** [comment]
Thank you @pujavs ,@smansoft 
working fine .

![image](https://user-images.githubusercontent.com/5729240/235098267-b980ce70-a3b0-4b8a-9f2f-7934b2c12bdd.png)
