### ISSUE TITLE
docs: how to run java tests against a setup

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#5514]
A possible related issue https://github.com/JanssenProject/jans/issues/2876

We need a clear documentation added detailing how to run tests against a setup. 

General outline:
1. Run linux setup with -t
2. prepare env and copy any profiles
3. trigger `mvn clean compile install`

**Comment by ossdhaval** [comment]
Instructions merged using the PR above are good to go based on tests on local lxd. **They give same results as tests run on Jenkins builds.**

In the most recent run on the local setup done using documented instructions, the result was
```
Tests run: 1839, Failures: 251, Errors: 0, Skipped: 9
```

241 of the 251 failures were due to Errors like the first error shown below. And then there were other errors too as listed. But all these tests were passing when run individually. So, actually zero tests failed. All these errors (especially the timeout errors) seem to be happening due to possible performance issues in my local lxd container as tests are passing individually.

Error (5) is not due to timeout but it is failing on the Jenkins build as well. Build #10082.

Types of erros in the logs:

(1)

BackchannelAuthenticationPingMode.idTokenHintAlgA256KWEncA256GCM:2588->BaseTest.authenticateResourceOwnerAndGrantAccess:441->BaseTest.authenticateResourceOwnerAndGrantAccess:450->BaseTest.authenticateResourceOwnerAndGrantAccess:460->BaseTest.authenticateResourceOwnerAndGrantAccess:480->BaseTest.acceptAuthorization:608->BaseTest.waitForRequredElementLoad:587 » Timeout Expected condition failed: waiting for io.jans.as.client.BaseTest$$Lambda$302/0x00000001007dbc40@131b8735 (tried for 30 second(s) with 1000 milliseconds interval)

(2)

PersistClientAuthorizationsHttpTest.doNotPersistAuthorizationWhenPreAuthorized:461 The scope is null expected object to not be null

(3)

AuthorizationResponseModeFragmentJwtResponseTypeTokenEncryptedHttpTest.testAlgA128KWEncA128GCM:61->BaseTest.authorizationRequest:1225->BaseTest.authoriz    ationRequest:1241 expected object to not be null

(4)

AuthorizeRestWebServiceHttpTest.requestAuthorizationDenyAccessThenGrantAccess:2189->BaseTest.authenticateResourceOwnerAndDenyAccess:708 » NoSuchElement     Unable to locate element with ID: 'authorizeForm:doNotAllowButton'

(5)

[ERROR]   RegistrationWithSoftwareStatementTest.requestClientAssociate2:245 Unexpected response code: {
    "error_description": "The software_statement is malformed or invalid. CorrelationId: dcd4cc5e-22f1-45c9-b2ac-6b6000ce364b",
    "error": "invalid_software_statement"
} expected [201] but found [400]

**Comment by yuriyz** [comment]
@ossdhaval under "Build #10082" do you refer to this build ? If yes, I see there only 2 failures. If no, can you provide link so it's more clear from where we got `251` failures?

https://jenkins.jans.io/jenkins/job/jans-auth-server/10082/testngreports/

![image](https://github.com/JanssenProject/jans/assets/2013070/61ee5aa5-1190-4ebf-ab14-2914c1066c78)

**Comment by ossdhaval** [comment]
@yuriyz 

Yes, I am referring to the same build. That Jenkins build has only two failures as can be seen in the report. So nothing to investigate there. 

251 failures are in my local test run. Most of them seem to be due to performance-related issues so can be ignored as we can expect them to pass in GH setup.
