### ISSUE TITLE
fix(jans-tui): when assign introspection script to client it writes script name instead of DN (AS expects DN).

### ISSUE THREAD

**Issue by mmrraju** [JanssenProject/jans#6598]
**Describe the bug**
Introspection script is not invoked for associate client.

**To Reproduce**
Steps to reproduce the behavior using Jans TUI:
1. Enable `Scripts > introspection_sample` , modify the script and prints something in the log.
2. Add this script to the associated client
3. save and exit.
4. Get token `curl -k -u 'clientId:pass' -k -d grant_type=client_credentials https://<host>/jans-auth/restv1/token`
5. And see token introspection `curl -k -X 'GET'   'https://<host>/jans-auth/restv1/introspection?token=xxx..&response_as_jwt=false'   -H 'accept: application/json' -H   "Authorization: Bearer xxx..."`

**Expected behavior**
Introspection script must be called during Access Token creation. 

**Screenshots**
![Screenshot from 2023-11-22 00-15-27](https://github.com/JanssenProject/jans/assets/43112579/a0c6507a-9c09-4f2a-8188-df5b3f23510c)

  - Version [v1.0.21.nightly]

**Comment by yuriyz** [comment]
@mmrraju can you attach full log and also LDIF/JSON of client ?

**Comment by devrimyatar** [comment]
I created a sample script

![scr](https://github.com/JanssenProject/jans/assets/6398752/2bbdbd06-2f2d-4f2e-8c37-9c69da8df208)

Attributes of this script in ldap is

![scr_attr](https://github.com/JanssenProject/jans/assets/6398752/62fe8772-afd8-4b39-beef-9201862def0e)

I think it is better to modify *Client Scripts* tabl of client so that it provides a checkbox list providing enabled scripts. This way no typo will occur.

**Comment by yuriyz** [comment]
On your screen it looks correct. It is DN. How did @mmrraju get name there ?

@devrimyatar it is good idea. Because Introspection field should accept only Introspection scripts and not some other type of scripts. So it makes perfect sense to me. However it is just UI thing, at the end we should have DN in `jansAttrs`.

**Comment by devrimyatar** [comment]
https://github.com/JanssenProject/jans/assets/6398752/e1fdf915-aceb-4613-84bc-b37eb21eec77

**Comment by yuriyz** [comment]
@mmrraju please test and report in support ticket if everything looks good.

**Comment by mmrraju** [comment]
sure, thanks.
