### ISSUE TITLE
fix(jans-tui): `Post Auth` and `Spontaneous Scope` script type are not appearing in Script Type list via Jans TUI

### ISSUE THREAD

**Issue by mmrraju** [JanssenProject/jans#6615]
**Describe the bug**
`Post Auth` and `Spontaneous Scope` script type are not appearing in Script Type list via Jans TUI.
According to [docs](https://docs.jans.io/head/admin/developer/scripts/). All Script type should be appeared in `Script Type` list via Jans TUI.

**To Reproduce**
Steps to reproduce the behavior using Jans TUI:
1. Go to **Scripts> Add scripts> Script Type**

**Expected behavior**
All script Type should appear in the drop-down list.

**Version [v1.0.21.nightly]**

**Comment by devrimyatar** [comment]
@mmrraju It is not related to TUI. When you enter scripts page, TUI queries endpoint `/api/v1/config/scripts/types` of config-api for script types:

https://github.com/JanssenProject/jans/blob/main/jans-cli-tui/cli_tui/plugins/060_scripts/main.py#L51-L64

And then uses it to populate dropdown list:

https://github.com/JanssenProject/jans/blob/main/jans-cli-tui/cli_tui/plugins/060_scripts/edit_script_dialog.py#L126-L130

@pujavs Please update config-api so that it returns all script types
