### ISSUE TITLE
config-api SCIM extension user endpoint

### ISSUE THREAD

**Issue by mbaser** [JanssenProject/jans#664]
**Describe the bug**
Jans Config-API SCIM extension user endpoint is missing

**To Reproduce**
1.  Install jans-ce (with install.py)
2. Check endpoint https://snap.gluu.org/jans-config-api/scim/user with curl
4. See error:
```
# curl -k https://snap.gluu.org/jans-config-api/scim/user
RESTEASY003210: Could not find resource for full path: https://snap.gluu.org/jans-config-api/scim/user
```

**Expected behavior**
The server should return a json output
**Screenshots**
Here is jans-cli output
![Screenshot_2022-01-21_14-54-17](https://user-images.githubusercontent.com/6398752/150522950-8edd80e2-0078-432b-b73e-bf574ed76adc.png)

**Desktop (please complete the following information):**
  - OS: ubuntu-20
  - Browser curl

**Comment by pujavs** [comment]
Jetty issues, On removing admin-plugin..jar  from jans-config-api.xml resolves the issue. 
However we need both plugins, checking further

**Comment by pujavs** [comment]
This issue is not happening now as admin-ui plugin is removed. However will find a solution.
![image](https://user-images.githubusercontent.com/43700552/153621219-56275838-db2d-4e5c-b3b6-f774e0faff85.png)

**Comment by pujavs** [comment]
@mbaser, the issue is due to multiple `extraClasspath` entry in jans-config-api.xml. Rather than multiple entry there should be only one `extraClasspath` entry with comma separated jars
### Incorrect way:
<?xml version="1.0"  encoding="ISO-8859-1"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_0.dtd">
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
    <Set name="contextPath">/jans-config-api</Set>
    <Set name="war">
        <Property default="." name="jetty.webapps" />/jans-config-api.war
    </Set>
    <Set name="extractWAR">true</Set>
**<Set name="extraClasspath">/opt/jans/jetty/jans-config-api/custom/libs/scim-plugin.jar</Set>
<Set name="extraClasspath">/opt/jans/jetty/jans-config-api/custom/libs/admin-ui-plugin-distribution.jar</Set>**</Configure>

### Correct way:
<?xml version="1.0"  encoding="ISO-8859-1"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_0.dtd">
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
    <Set name="contextPath">/jans-config-api</Set>
    <Set name="war">
        <Property default="." name="jetty.webapps" />/jans-config-api.war
    </Set>
    <Set name="extractWAR">true</Set>
**<Set name="extraClasspath">/opt/jans/jetty/jans-config-api/custom/libs/scim-plugin.jar,/opt/jans/jetty/jans-config-api/custom/libs/admin-ui-plugin-distribution.jar</Set>**</Configure>

### Testing with multiple entry:
![Issue#664_Fix](https://user-images.githubusercontent.com/43700552/155978707-e1e63f75-12ab-4457-a2aa-df74ab747b6b.JPG)
