### ISSUE TITLE
BUG: after monorepo related changes jenkins triggers all builds even if commit is not related to given project

### ISSUE THREAD

**Issue by yuriyz** [JanssenProject/jans#742]
**Describe the bug**

After commit to jans-config-api jenkins triggering many jobs and perform redundant work in this way not allowing "right" jobs to start.

![image](https://user-images.githubusercontent.com/2013070/151847929-c06139d1-0718-4707-a694-4a8874ff1c24.png)

**Comment by ossdhaval** [comment]
@yuriyz 

I am planning to use [sparse-checkout](https://github.blog/2020-01-17-bring-your-monorepo-down-to-size-with-sparse-checkout/) to fix this. 
Basically, this will only checkout a specific directory for which we want build to be triggered. Then as usual, Jenkins will check if there are any changes in that directory and trigger build if it finds any changes. As a side-effect, this will also reduce size of working directory for each job.
Though this feature is marked experimental in Git, it is there since many years and has been further enhanced in 2020.

**Comment by yuriyz** [comment]
Question is why when we commit to lets say jans-auth-server we don't get such effect. It means that it is triggered only for some projects (e.g. jans-config-api). Thus do we really need sparse-checkout or maybe investigate mis-configurations in jobs?

Otherwise sparse-checkout looks as clean way to proceed.

**Comment by ossdhaval** [comment]
I think `jans-auth-server` is not an exception either. See [this fido build](https://jenkins.jans.io/jenkins/job/jans-fido2/1041/changes#10f6ec1c7e52210a113907dc8c0552f67fa51cba) got triggered due to changes in `jans-auth-server`.

**Comment by ossdhaval** [comment]
Also, just having sparse-checkout is not doing the trick. I may need to add shell script to detect changed root directory and trigger accordingly. Work in progress.

**Comment by ossdhaval** [comment]
As discussed over chat, we are now solving this issue via a new pipeline job.

**Comment by ossdhaval** [comment]
Old issue that was fixed a more than a year back, with changes in the trigger and SCM polling configuration as per [chat](https://chat.gluu.org/direct/cymdMPNYwbNcFgXEEst4T4ja3aWKQqi9Sm?msg=CNkNR2XNc4kwfJJFW). Also, [jobs currently in Jenkins](https://jenkins.jans.io/jenkins/job/jans-link/367/) are not showing this behavior.
