### ISSUE TITLE
feat: allow to override ORM connection properties

### ISSUE THREAD

**Issue by yurem** [JanssenProject/jans#7816]
ORM should use environment/java variables with same names to override ORM configuration properties.

Also it should use environment variables like `CONNECTION_URI` to override properties like `connection.uri` and `connection-uri`

**Comment by ossdhaval** [comment]
> Here is example to override `connection.uri` from `/etc/default/jans-auth`:
> 
> java variables:
> 
> ```
> JAVA_OPTIONS="...-Dconnection.uri=jdbc:postgresql://localhost:5432/jansdb..."
> ```
> 
> env variables
> 
> ```
> export CONNECTION_URI=jdbc:postgresql://localhost:5432/jansdb
> ```

Hi @yurem 

I am updating documents for these changes.

I have a quick question: The steps above will change the property value **only** for `jans-auth` module. 
But same has to be done for all the other modules which use ORM so that all Janssen Server modules point to the same DB. Is this understanding correct?

**Comment by moabu** [comment]
@ossdhaval its actually the opposite in VM. If you pass that env globally it will change for all the modules.

**Comment by yurem** [comment]
right, it depends on scope where you export env properties. Global properties will be used in all jans app. If you need to export them for specific app you can use `/etc/default/jans-xyz` for example
