### ISSUE TITLE
feat(documentstore): save document should return a handle to created asset or an identifier

### ISSUE THREAD

**Issue by pujavs** [JanssenProject/jans#7920]
Right now the document store only returns a boolean true or false. Its should return a way to get to the created resource.

**Comment by yurem** [comment]
@shekhar16 We can update  DocumentStore `saveXYZ..` API to return String instead of boolean. We don't need to backport this to Gluu CE.

LocalDocumentStoreProvider should return path to stored file instead of boolean
JcaDocumentStoreProvider should return `normalizedPath` of stored file instead of boolean
DbDocumentStoreProvider should return `inum`of stored file instead of boolean

**Comment by yurem** [comment]
Updated API returns path specified in save/update/rename

**Comment by yurem** [comment]
implemented
