### ISSUE TITLE
fix(jans-cli): Duplicate lines for schema definition of SCIM in Jans CLI

### ISSUE THREAD

**Issue by imShakil** [JanssenProject/jans#9371]
# Behaviour

There are duplicate lines for schema definition of SCIM info in Jans CLI. 

# How to Produce?

Please run the jans-cli in scim mode as below:

```
/opt/jans/jans-cli/config-cli.py -scim --info User
/opt/jans/jans-cli/config-cli.py -scim --info Group
```

# Screenshots

<img width="576" alt="Screenshot 2024-09-05 at 08 21 08" src="https://github.com/user-attachments/assets/f5dd5ded-2966-4657-a9eb-71d48cf2e812">

**Comment by devrimyatar** [comment]
This is due to two duplicate content definitions in **requestBody**, namely **application/scim+json** and **application/json**. For example:

![image](https://github.com/user-attachments/assets/dd92602a-46f9-4fb7-abdb-d34750759767)

@jgomer2001 Please comment how to solve this? If not both **application/scim+json** and **application/json** are rquired, please delete one of them. If both required can you guide me how to fix this in CLI?

**Comment by jgomer2001** [comment]
these two content types are normative and should not be changed

From CLI perspective you can take just one and ignore the other
