### ISSUE TITLE
fix(jans-tui): Saving a script as a file is not working

### ISSUE THREAD

**Issue by maduvena** [JanssenProject/jans#9979]
**Describe the bug**
Scripts can be saved in db or as a file. The file option is not working.
Tested on Local VM, I dont know how this will translate on Cloud.

**To Reproduce**
1. Go to 'tui'
2. Under scripts, select any script and attempt to save the contents as a file 
3. Check db

**Comment by devrimyatar** [comment]
@maduvena @pujavs I added a test script. This is what TUI sent to config-api
```JSON
{
  "inum": "",
  "scriptType": "application_session",
  "enabled": false,
  "name": "test",
  "description": "test",
  "locationType": "file",
  "locationPath": "/opt/jans/python/libs/a.py",
  "programmingLanguage": "python",
  "level": 0,
  "internal": false,
  "modified": false,
  "revision": 1,
  "script": "import os\nfor i in os.listdir('/tmp'):\n    print(i)",
  "moduleProperties": [
    {
      "value1": "location_type",
      "value2": "file"
    }
  ]
}
```

It seems config-api ignores location. It saves to database.

**Comment by pujavs** [comment]
That is correct `config-api` custom-script functionality is entirely DB driven. This seems to be new requirement.
@yurem can we use document-store since there can be distributed env.

**Comment by yurem** [comment]
Behavior explained in this issue is opposite to initial idea of using `file` location type.

When we use file location type we follow next steps:
1. Register new script type and specify it location
2. Put script manually to file system
3. Apply changes to script on disk
4. Script manager do it reload on file modification within 30 seconds

Why instead of modifying script file you call config-api? This not really uses this location type in this case. It's looks like DB location time is better conform this.

**Comment by devrimyatar** [comment]
@yurem What do you think about removing location type from TUI.

**Comment by yurem** [comment]
@devrimyatar if we remove it from TUI we can't add script with this location type. And we will loss this functionality.

@pujavs @devrimyatar what do you think about changing this part of request:
```
  "locationType": "file",
  "locationPath": "/opt/jans/python/libs/a.py",
  "script": "import os\nfor i in os.listdir('/tmp'):\n    print(i)",
```

to:
```
  "locationType": "file",
  "filelName": "a.py",
```

After getting this request config-api should build `locationPath` from 2 parts: `script_custom_folder_path_for_file_type` + `fileName`
This will be more secure because we not allow to run any python script from file system

Also developers still can use `locationType=file`

**Comment by devrimyatar** [comment]
@yurem `fileName` is fine for me. It is up to @pujavs to implement.

**Comment by devrimyatar** [comment]
@pujavs config-api still not working as explianed by @yurem in comment https://github.com/JanssenProject/jans/issues/9979#issuecomment-2449708706
